task:
  freebsd_instance:
    cpu: 8
    memory: 32G
    matrix:
      # image: freebsd-12-1-release-amd64 # EOL
      # image: freebsd-12-2-release-amd64
      - image: freebsd-13-0-release-amd64
      - image: freebsd-14-0-snap-amd64

  env:
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[!0f42e3f70fd51cdeddfe7e98160982fc9efe7e8a26869b725fcd5de05d067a7100b994cf52f0f1b470a983148e0b8ec2!]
    
  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  # only_if: $CIRRUS_TAG !=~ 'continuous.*'
  # Do not build tags, only commits
  only_if: $CIRRUS_TAG !=~ '..*'

  env:
    matrix:
      DESKTOP: 'hello'

  env:
    matrix:
      arch: 'amd64'

  Environment_script:
    - env
    - kldload zfs.ko
    - kldload tmpfs.ko || true
    - kldload nullfs.ko || true
    - kldload geom_uzip.ko || true
    - pkg install -y pkg git-lite zsync wget sha bash zip devel/py-xdg librsvg2 ca_root_nss # qemu-devel uefi-edk2-qemu-x86_64
    - mkdir -p /usr/local/furybsd/uzip /usr/local/furybsd/cdroot/
    - mount -t tmpfs tmpfs /usr/local/furybsd/uzip
    - mount -t tmpfs tmpfs /usr/local/furybsd/cdroot/
    
  Build_script:
    - export VER=$(uname -r | cut -d "-" -f 1)
    # if [ "$VER" = "12.1" ] ; then export PERSIST_NEW_BUILDNUMBER="YES" ; fi # Only persist incremented build number for one of the builds in the matrix
    - export PERSIST_NEW_BUILDNUMBER="YES"
    - wget -c -q https://github.com/helloSystem/buildnumbers/releases/download/initial/buildnumbers
    - chmod +x ./buildnumbers
    - export BUILDNUMBER=$(RELEASE_ID_FOR_STORAGE=33980128 ./buildnumbers)
    - /bin/sh -x ./build.sh "${DESKTOP}" || true # FIXME: Why does this return an error even though the ISO succeeded?
    - df -h
    - ls -lh /usr/local/furybsd/*.iso || false # Error out if ISO was not produced to mitigate the above
    # ( cd /usr/local/furybsd/ ; zsyncmake *.iso )
    
  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1) # No way to pass on from Build_script to Upload_script?
    - ls -lh /usr/local/furybsd/
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -prerelease -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -b "This is an experimental __UNTESTED__ build for developers, it may not even boot." -c "${CIRRUS_CHANGE_IN_REPO}" "${CIRRUS_BRANCH}"-"${VER}" /usr/local/furybsd/ ; esac
